// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvx-lS0xH54Jae6ABmVHp1PEeChNR1fWY',
    appId: '1:249385856799:web:f91c67a7899ffc8f038a2a',
    messagingSenderId: '249385856799',
    projectId: 'family-tree-5eb1d',
    authDomain: 'family-tree-5eb1d.firebaseapp.com',
    storageBucket: 'family-tree-5eb1d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmKbM0sOzdUVHsgvuDPqMLO7tmurE9frY',
    appId: '1:249385856799:android:e69ce1bab2e39e05038a2a',
    messagingSenderId: '249385856799',
    projectId: 'family-tree-5eb1d',
    storageBucket: 'family-tree-5eb1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4OVKd8gWYYyXkKRy2QpLHP0GE4n1Es4k',
    appId: '1:249385856799:ios:2b253fbe9c311197038a2a',
    messagingSenderId: '249385856799',
    projectId: 'family-tree-5eb1d',
    storageBucket: 'family-tree-5eb1d.appspot.com',
    iosClientId: '249385856799-toql3m373uj3amaia3vs890coeicngjt.apps.googleusercontent.com',
    iosBundleId: 'com.example.familyTree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4OVKd8gWYYyXkKRy2QpLHP0GE4n1Es4k',
    appId: '1:249385856799:ios:2b253fbe9c311197038a2a',
    messagingSenderId: '249385856799',
    projectId: 'family-tree-5eb1d',
    storageBucket: 'family-tree-5eb1d.appspot.com',
    iosClientId: '249385856799-toql3m373uj3amaia3vs890coeicngjt.apps.googleusercontent.com',
    iosBundleId: 'com.example.familyTree',
  );
}
